### ISSUE TITLE
What is the expected behavior on app reload?

### ISSUE THREAD

**Issue by geirman** [lawnstarter/react-native-hotspot#3]
Hey, this looks like a really cool library. Thanks for sharing. It's not clear exactly how this works. From the demo, it looks like...

1. First tap, does whatever you like... alert the user with more info about the feature.
2. After tap, the hotspot disappears...but for how long? Forever? Until the app is loaded again?
3. Will the hotspot persist forever until the user taps it for the first time?

It would be helpful to understand the expected behavior.

**Comment by lfkwtz** [comment]
Hey @geirman, I updated the readme to clarify that a bit - but essentially the actions that occur once a hotspot is touched are fully up to you.

Ideally, you'll probably want to save something to local storage and/or make an api call to mark a hotspot as "seen".

This is a library we use internally that I stripped down a bit to make it more flexible for open source, but in doing so it may not be stable enough for production yet.

Feel free to play around with it and submit any prs or documentation updates that may be useful.
